if [[ $TERM == xterm ]]; then
 export TERM='xterm-256color'
fi

#ZSH_THEME="bira"

# this settings require downloading
# fonts
# refer to https://gist.github.com/kevin-smets/8568070
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="awesome-patched"
# run > p10k configure if you want to configure
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# visit https://github.com/Powerlevel9k/powerlevel9k/wiki/Stylizing-Your-Prompt
# for more info
# you can use getColorCode {foreground|background} to see more colors
POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=187

export EDITOR=vim

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh


for script in ~/.zsh/*.sh
do
  [ -x "$script" ] || continue
  source $script
done

if [ -e ~/.zshrc_local ]
then
  source ~/.zshrc_local
fi

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=008, bold'


# Load Git completion
zstyle ':completion:*:*:git:*' script ~/dotfiles/zsh/git-completion.bash
fpath=(~/.zsh $fpath)

autoload -Uz compinit && compinit
