if [[ $TERM == xterm ]]; then
 export TERM='xterm-256color'
fi

ZSH_THEME="bira"

export EDITOR=vim

plugins=(
  git
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh



ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=008, bold'

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/dotfiles/zsh/git-completion.bash
fpath=(~/.zsh $fpath)

autoload -Uz compinit && compinit
